WeaponSkins= {}
WeaponSkins[ 1 ] = {
[ 0 ] = { name = "default", skin = "" },
[ 1 ] = { name = "APC Camo", skin = "models/de_piranesi/pi_apc" },
[ 2 ] = { name = "Combine #1", skin = "models/combine_dropship/combine_dropship01" },
[ 3 ] = { name = "Combine #2", skin = "models/combine_helicopter/combine_helicopter01" },
[ 4 ] = { name = "Combine #3", skin = "models/combine_room/combine_monitor002" },
[ 5 ] = { name = "Combine #4", skin = "models/combine_turrets/ceiling_turret/combine_gun003" },
[ 6 ] = { name = "Combine #5", skin = "models/combine_citadel/combine_citadel001" },
[ 7 ] = { name = "Combine #6", skin = "models/combine_apc/apc01blue_nofog" },
[ 8 ] = { name = "Tan Blue", skin = "models/props_interiors/sofa01" },
[ 9 ] = { name = "Winch", skin = "models/props_canal/winch02" },
[ 10 ] = { name = "Tetanus", skin = "models/props_junk/phys_objects01a" },
[ 11 ] = { name = "Metal Flavour 1#", skin = "models/props_pipes/valvewheel001_skin2" },
[ 12 ] = { name = "Metal Flavour 2#", skin = "models/props_pipes/valvewheel001_skin1" },
[ 13 ] = { name = "Scratchy Orange", skin = "models/props_rooftop/letter_sign001" },
[ 14 ] = { name = "Elder Yellow", skin = "models/props/cs_assault/water_tower" },
[ 15 ] = { name = "White Compound", skin = "models/props/cs_militia/van1" },
[ 16 ] = { name = "Conductivity", skin = "models/props/de_nuke/nucleartestcabinetdirty" },
[ 17 ] = { name = "Elder Alloy", skin = "models/props/de_port/tankoil1b" },
[ 18 ] = { name = "Algebra", skin = "models/props/de_tides/truck001c_01" },
[ 19 ] = { name = "Alloy", skin = "phoenix_storms/future_vents" },
[ 20 ] = { name = "Black Compound", skin = "models/crane_docks/crane_chair" },
color = Color( 33, 255, 0, 255 ),
}
WeaponSkins[ 2 ] = {
[ 1 ] = { name = "Stained Reflection", skin = "models/props/de_nuke/railing_ramp_b" },
[ 2 ] = { name = "Strap Jacket", skin = "models/kleiner/players_sheet" },
[ 3 ] = { name = "Waste", skin = "models/props_wasteland/boat_fishing01a" },
[ 4 ] = { name = "Desert Oak", skin = "models/chairs/armchair" },
[ 5 ] = { name = "Water-Cooled", skin = "models/props_buildings/watertower_001c" },
[ 6 ] = { name = "Industrial", skin = "models/props_buildings/watertower_002a" },
[ 7 ] = { name = "Aggressor", skin = "models/props_citizen_tech/wind_mill_blade004b" },
[ 8 ] = { name = "Soda Pop", skin = "models/props_interiors/sodamachine01a" },
[ 9 ] = { name = "Highway Man", skin = "models/props_junk/trafficcone001a" },
[ 10 ] = { name = "Winter Steel", skin = "models/props_junk/trashdumpster02" },
[ 11 ] = { name = "Lab Blue", skin = "models/props_pipes/valve003_skin1" },
[ 12 ] = { name = "Shock Box", skin = "models/props_vehicle/generatortrailer01" },
[ 13 ] = { name = "Bullet Tray", skin = "models/props/cs_militia/reload_bullet_tray" },
[ 14 ] = { name = "Salvation Orange", skin = "models/props/de_nuke/lifepreserver" },
[ 15 ] = { name = "Volts", skin = "models/props/de_prodigy/transformer" },
[ 16 ] = { name = "Dried Out", skin = "models/props/de_prodigy/turret" },
color = Color( 22, 224, 255, 255 ),
}
WeaponSkins[ 3 ] = {
[ 1 ] = { name = "Charred #1", skin = "models/charple/charple2_sheet" },
[ 2 ] = { name = "Charred #2", skin = "models/charple/charple1_sheet" },
[ 3 ] = { name = "Charred #3", skin = "models/charple/charple3_sheet" },
[ 4 ] = { name = "Snowfall Camo", skin = "models/cstrike/t_arctic" },
[ 5 ] = { name = "White Elite", skin = "models/combine_soldier/combine_elite" },
[ 6 ] = { name = "Pure Light", skin = "models/lamps/torch" },
[ 7 ] = { name = "Black light", skin = "phoenix_storms/futuristictrackramp_1-2" },
[ 8 ] = { name = "Mellow Metal #1", skin = "models/props_interiors/refrigeratordoor01a" },
[ 9 ] = { name = "Mellow Metal #2", skin = "models/props_interiors/refrigeratordoor02a" },
[ 10 ] = { name = "Garbage Man", skin = "models/props_junk/garbage001a_01" },
[ 11 ] = { name = "Junk Food", skin = "models/props_junk/food_used" },
[ 12 ] = { name = "Silver Aged Banana", skin = "models/props/de_nuke/railing_ramp_a" },
color = Color( 53, 63, 255, 255 ),
}
WeaponSkins[ 4 ] = {
[ 1 ] = { name = "Facepunch", skin = "phoenix_storms/barrel" },
[ 2 ] = { name = "Conspiracy", skin = "models/xqm/2deg360_diffuse" },
[ 3 ] = { name = "Lambda Touched", skin = "models/hevsuit/hevsuit_sheet" },
[ 4 ] = { name = "Sprite", skin = "models/xqm/hoverboard_diffuse" },
[ 5 ] = { name = "Bad Geometry", skin = "models/xqm/squaredmatinverted" },
[ 6 ] = { name = "Jungle Glass", skin = "models/props_junk/glassbottle01a" },
[ 7 ] = { name = "Brimstone", skin = "models/props/de_nuke/nucleartestcabinet_ref" },
[ 8 ] = { name = "Black Bubblegum", skin = "models/props/de_prodigy/wall_console2_ref" },
color = Color(  174, 68, 255, 255 )
}
WeaponSkins[ 5 ] = {
[ 1 ] = { name = "Meat Fantasy", skin = "models/flesh" },
[ 2 ] = { name = "Xen", skin = "models/barnacle/barnacle_sheet" },
[ 3 ] = { name = "Evolution", skin = "models/ichthyosaur/ichthyosaur_sheet" },
[ 4 ] = { name = "Demon Touched", skin = "models/zombie_poison/poisonzombie_sheet" },
color =  Color( 255, 38, 0, 255 ),
}